# Generated by Django 5.2.6 on 2025-11-18 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qnas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qna',
            name='question',
            field=models.TextField(),
        ),
    ]
