# Generated by Django 5.2.6 on 2025-11-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_qna_user_alter_qna_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='answer',
            field=models.TextField(blank=True, help_text='AI 답변', null=True),
        ),
        migrations.AlterField(
            model_name='qna',
            name='question',
            field=models.TextField(help_text='사용자 질문'),
        ),
    ]
