# Generated by Django 5.2.6 on 2025-09-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_id', models.IntegerField()),
                ('title', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'summary',
            },
        ),
    ]
