# Generated by Django 5.2.6 on 2025-11-11 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_remove_article_originalurl_article_url'),
        ('summary', '0002_alter_summary_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('group_index', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='summary',
            name='article_id',
        ),
        migrations.AddField(
            model_name='summary',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='article.article'),
        ),
        migrations.AddField(
            model_name='summary',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='summary.summarygroup'),
        ),
    ]
