# Generated by Django 5.2.6 on 2025-11-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_summarygroup_remove_summary_article_id_and_more'),
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='terms',
            field=models.ManyToManyField(blank=True, related_name='summaries', to='term.term'),
        ),
    ]
