# Generated by Django 5.2.6 on 2025-11-12 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('summary', '0003_summarygroup_remove_summary_article_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('choice_type', models.PositiveSmallIntegerField(choices=[(3, 'Multiple Choice (3)'), (5, 'Multiple Choice (5)')], default=3)),
                ('summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_quizzes', to='summary.summary')),
            ],
            options={
                'db_table': 'quiz_multiple_choice',
            },
        ),
        migrations.CreateModel(
            name='OXQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('correct_answer', models.BooleanField(help_text='O=True, X=False')),
                ('summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_quizzes', to='summary.summary')),
            ],
            options={
                'db_table': 'quiz_ox',
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.multiplechoicequiz')),
            ],
            options={
                'db_table': 'quiz_option',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ShortAnswerQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('correct_answer', models.CharField(max_length=255)),
                ('summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_quizzes', to='summary.summary')),
            ],
            options={
                'db_table': 'quiz_short_answer',
            },
        ),
        migrations.CreateModel(
            name='UserQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('ox_answer', models.BooleanField(blank=True, null=True)),
                ('text_answer', models.CharField(blank=True, max_length=255)),
                ('is_correct', models.BooleanField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.quizoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_quiz_answer',
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
