# Generated by Django 5.2.6 on 2025-11-12 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizanswer',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'quiz'), ('model', 'oxquiz')), models.Q(('app_label', 'quiz'), ('model', 'multiplechoicequiz')), models.Q(('app_label', 'quiz'), ('model', 'shortanswerquiz')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
