# Generated by Django 5.2.6 on 2025-11-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='userAnswer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
