# Generated by Django 5.2.6 on 2025-11-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_userquizanswer_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequiz',
            name='choice_type',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Multiple Choice (4)')], default=4),
        ),
    ]
