# Generated by Django 5.2.6 on 2025-11-11 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_useranswer'),
        ('summary', '0003_summarygroup_remove_summary_article_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='ox',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='userAnswer',
        ),
        migrations.AddField(
            model_name='quiz',
            name='correct_bool',
            field=models.BooleanField(blank=True, help_text='OX 문제일 때만 사용 (O=True, X=False)', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='correct_text',
            field=models.CharField(blank=True, help_text='객관식/단답형 문제일 때만 사용', max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('OX', 'OX'), ('MC3', 'Multiple Choice (3)'), ('MC5', 'Multiple Choice (5)'), ('SC', 'Short Answer')], default='OX', max_length=4),
        ),
        migrations.AddField(
            model_name='quiz',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='summary.summary'),
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('text', models.CharField(max_length=255)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.quiz')),
            ],
            options={
                'db_table': 'quiz_option',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ox_answer', models.BooleanField(blank=True, help_text='OX 문제에서 사용', null=True)),
                ('text_answer', models.CharField(blank=True, help_text='단답형 문제에서 사용', max_length=255)),
                ('is_correct', models.BooleanField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.quizoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_quiz_answer',
                'unique_together': {('user', 'quiz')},
            },
        ),
    ]
