# Generated by Django 5.2.6 on 2025-11-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_multiplechoicequiz_choice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequiz',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oxquiz',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shortanswerquiz',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
