# Generated by Django 5.2.6 on 2025-09-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=255, null=True)),
                ('journal', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
