# Generated by Django 5.2.6 on 2025-11-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='url',
        ),
        migrations.AddField(
            model_name='article',
            name='originalUrl',
            field=models.CharField(max_length=511, null=True),
        ),
    ]
