# Generated by Django 5.2.6 on 2025-11-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_article_url_article_originalurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='originalUrl',
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
